---
# tasks file for remediations

- name: Check if the system is RHEL 8
  ansible.builtin.assert:
    that: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 8
    msg: "This role is only applicable to RHEL 8"
  tags: remediate

- name: Remediate the system
  ansible.builtin.include_tasks: "{{ remediation_item }}.yml"
  loop: "{{ remediation_playbooks }}"
  loop_control:
    loop_var: remediation_item
  when: remediation_item in remediation_todo
...
